/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: ["class", '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        base: "var(--bg-base)",
        surface: "var(--bg-surface)",
        elevated: "var(--bg-elevated)",
        inset: "var(--bg-inset)",
        "card-bg": "var(--card-bg)",
        "item-bg": "var(--item-bg)",
        "sidebar-bg": "var(--sidebar-bg)",
        "navbar-bg": "var(--navbar-bg)",
        "text-primary": "var(--text-primary)",
        "text-secondary": "var(--text-secondary)",
        "text-muted": "var(--text-muted)",
        "text-on-accent": "var(--text-on-accent)",
        "border-subtle": "var(--border-subtle)",
        "border-default": "var(--border-default)",
        accent: "var(--accent)",
        "accent-hover": "var(--accent-hover)",
        "accent-subtle": "var(--accent-subtle)",
        danger: "var(--danger)",
        "danger-hover": "var(--danger-hover)",
        "danger-subtle": "var(--danger-subtle)",
        success: "var(--success)",
        "success-hover": "var(--success-hover)",
        "success-subtle": "var(--success-subtle)",
        warning: "var(--warning)",
        "warning-hover": "var(--warning-hover)",
        "warning-subtle": "var(--warning-subtle)",
      },
    },
  },
  plugins: [],
};
